name: Bug Report
description: Please do not use bug reports for support issues
labels: [bug, needs-review]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        |
        Note: Please use [Discord](https://tautulli.com/discord) for support issues.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: input
    id: version-tautulli-remote
    attributes:
      label: Tautulli Remote Version
      description: What version of Tautulli Remote are you running?
      placeholder: ex. v2.11.2
    validations:
      required: true
  - type: input
    id: version-tautulli
    attributes:
      label: Tautulli Version
      description: What version of Tautulli are you running?
      placeholder: ex. v2.7.5
    validations:
      required: true
  - type: input
    id: mobile-device
    attributes:
      label: Mobile Device
      description: What device are you using?
      placeholder: ex. Pixel 5, iPhone 12
    validations:
      required: true
  - type: input
    id: mobile-os
    attributes:
      label: Mobile OS
      description: What OS version is your device running?
      placeholder: ex. Android 11, iOS 14
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
