name: Bug Report
description: Please do not use bug reports for support issues.
labels: [status:awaiting-triage, type:bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
