name: Bug Report
description: Please do not use bug reports for support issues.
labels: [status:awaiting-triage, type:bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Make sure to close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.
        THIS IS NOT THE PLACE TO ASK FOR SUPPORT! Please use [Discord](https://tautulli.com/discord) for support issues.
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: A clear and concise description of what you expected to happen.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: Provide screenshots to help explain your problem.
  - type: textarea
    id: relevant
    attributes:
      label: Relevant Settings
      placeholder: |
        - eg. Plex Media Server IP address/port/checkboxes/proxy/etc.
        - eg. Notification agent configuration/triggers/conditions/text/delay/grouping/etc.
        - eg. Newsletter agent configuration/checkboxes/template/etc.
        - Other settings
  - type: input
    id: version
    attributes:
      label: Tautulli Version
      placeholder: ex. v2.7.5 (check Tautulli Settings > Help & Info page)
    validations:
      required: true
  - type: input
    id: branch
    attributes:
      label: Git Branch
      placeholder: ex. master (check Tautulli Settings > Help & Info page)
    validations:
      required: true
