name: Bug Report
description: Please do not use bug reports for support issues.
labels: [status:awaiting-triage, type:bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Make sure to close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.
        THIS IS NOT THE PLACE TO ASK FOR SUPPORT! Please use [Discord](https://tautulli.com/discord) for support issues.
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
